

hosts = {
	"vmHost0" => "192.168.3.14"
}

Vagrant.configure("2") do |config|
	hosts.each do |name, ip|
		config.vm.box = "ubuntu/trusty32"
		config.vm.hostname = name
		config.vm.network :private_network, ip: ip
		config.vm.provider "virtualbox" do |v|
			v.name = name
			v.memory = "1024"
			v.cpus = 2
		end
	end
end


# hosts = {
#    "vmHost2" => "192.168.3.33",
# }
 
# Vagrant.configure("2") do |config|
# 	hosts.each do |name, ip|
# 		config.vm.define name do |machine|
# 		    machine.vm.box = "ubuntu/trusty32"
# 		    machine.vm.hostname = "%s.example.org" % name
# 		    machine.vm.network :private_network, ip: ip
# 		    machine.vm.provider "virtualbox" do |v|
# 		    	v.name = name
# 		    	v.customize ["modifyvm", :id, "--memory", 200]
# 		    end
# 		end
# 	end
# end
